# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
     (modulesPath + "/installer/scan/not-detected.nix")
     ./hardware/gpu.nix
     ./hardware/kernel.nix
  ];

   # Bootloader
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelPackages = pkgs.linuxPackages_zen;
    # kernelPackages = pkgs.linuxPackages_latest;
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    initrd.kernelModules = [ ];
    initrd.availableKernelModules = [ 
      "xhci_pci"
      "ahci"
      "ohci_pci"
      "ehci_pci"
      "usb_storage"
      "sd_mod"
      "sr_mod"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/002b0d1f-f315-4b21-a33a-adbd38d23959";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2AD7-8CC5";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8d17cb32-61d9-45ef-9ffd-815d07a6723d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
